name: Release

on:
  push:
    tags:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      - name: substring-action
        id: tag-id
        uses: bhowell2/github-substring-action@v1.0.0
        with:
          value: ${{ github.ref }}
          index_of_str: "refs/tags/"

      - uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.tag-id.outputs.substring }}
          draft: true
          prerelease: true
          artifacts: ""
          generateReleaseNotes: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
